"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const promises_1 = __importDefault(require("fs/promises"));
const path_1 = __importDefault(require("path"));
const test_1 = require("@playwright/test");
const crypto_1 = require("crypto");
const DEFAULT_OPTIONS = {
    enabled: true,
    resultDetails: {},
    triggerReportGeneration: true,
    dryRun: false,
};
class ReporterPlaywrightReportsServer {
    constructor(options) {
        this.rpOptions = { ...DEFAULT_OPTIONS, ...options };
        if (this.rpOptions.enabled === false) {
            return;
        }
        if (!this.rpOptions.url) {
            throw new Error('[ReporterPlaywrightReportsServer] url is required, cannot run without it');
        }
        if (!this.rpOptions.reportPath) {
            throw new Error('[ReporterPlaywrightReportsServer] reportPath is required, cannot run without it');
        }
    }
    onBegin(config /*suite: Suite*/) {
        if (this.rpOptions.enabled === false) {
            return;
        }
        this.pwConfig = config;
        this.blobPath = path_1.default.join(process.cwd(), this.rpOptions.reportPath);
        this.blobName = path_1.default.basename(this.blobPath);
    }
    async onEnd( /*result: FullResult*/) {
        if (this.rpOptions.enabled === false) {
            return;
        }
        if (this.blobPath === undefined) {
            throw new Error('[ReporterPlaywrightReportsServer] Blob file path is absent. Results cannot be uploaded');
        }
        let buffer;
        try {
            buffer = await promises_1.default.readFile(this.blobPath);
        }
        catch (err) {
            console.error(err);
            throw new Error('[ReporterPlaywrightReportsServer] Blob file not found or cannot be loaded. Results cannot be uploaded');
        }
        const ctx = await test_1.request.newContext({
            extraHTTPHeaders: this.rpOptions.token !== undefined
                ? {
                    Authorization: this.rpOptions.token,
                }
                : {},
        });
        const resultDetails = this.rpOptions.resultDetails === undefined ? {} : this.rpOptions.resultDetails;
        // TODO: API client needed
        let resultResponse;
        const url = this.rpOptions.url.endsWith('/') ? this.rpOptions.url.slice(0, -1) : this.rpOptions.url;
        const shard = this.pwConfig.shard;
        if (this.rpOptions.dryRun === false) {
            const resp = await ctx.put(`${url}/api/result/upload`, {
                multipart: {
                    file: {
                        name: this.blobName ?? 'blob.zip',
                        mimeType: 'application/zip',
                        buffer: buffer,
                    },
                    ...resultDetails,
                    ...(shard ? { shardCurrent: shard.current, shardTotal: shard.total } : {}),
                    triggerReportGeneration: !this.rpOptions.triggerReportGeneration,
                },
            });
            resultResponse = (await resp.json()).data;
        }
        else {
            resultResponse = {
                savedResult: { resultID: (0, crypto_1.randomUUID)(), createdAt: '2021-01-01', size: '123', sizeBytes: 123 },
                generatedReport: null,
            };
        }
        console.debug('[ReporterPlaywrightReportsServer] blob result uploaded: ', resultResponse);
        // If we are not in a shard, we should trigger report generation with POST request, otherwise report will be generated by the server
        if (this.rpOptions.triggerReportGeneration === true) {
            let report;
            if (this.pwConfig.shard === null) {
                if (this.rpOptions.dryRun === false) {
                    report = await (await ctx.post(`${this.rpOptions.url}/api/report/generate`, {
                        data: {
                            resultsIds: [resultResponse.savedResult.resultID],
                            ...resultDetails,
                        },
                    })).json();
                }
                else {
                    report = {
                        reportUrl: '/data/report/123/index.html',
                    };
                }
            }
            else {
                console.log('[ReporterPlaywrightReportsServer] Shard detected, report will be generated by the server');
                report = {
                    reportUrl: `/api/serve/${resultResponse.generatedReport.reportId}/index.html`,
                };
            }
            console.log(`[ReporterPlaywrightReportsServer] 🎭 HTML Report is available at: ${this.rpOptions.url}${report.reportUrl}`);
        }
    }
}
exports.default = ReporterPlaywrightReportsServer;
